spring.datasource.url=jdbc:mysql://root:HLtKgDCffAeoZNmgyWLUKnSMRRHDXyZC@maglev.proxy.rlwy.net:52534/railway
spring.datasource.username=root
spring.datasource.password=HLtKgDCffAeoZNmgyWLUKnSMRRHDXyZC

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

server.port=${port:8081}
