spring.datasource.url=jdbc:mysql://root:CEiXWEktPxcemzJmRDtaftXFpzdKNKiX@shuttle.proxy.rlwy.net:19887/railway
spring.datasource.username=root
spring.datasource.password=CEiXWEktPxcemzJmRDtaftXFpzdKNKiX

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

server.port=${port:8081}
